### ISSUE TITLE
Add template for ViewModel PHP Classes

### ISSUE THREAD

**Issue by pocketprogrammer** [lfolco/phpstorm-m2-filetemplates#9]
ViewModels are the new best practice since 2.2 to extend block functionality using composition over inheritance. The basic idea is that you create a ViewModel class which implements `Magento\Framework\View\Element\Block\ArgumentInterface` and add it as an argument to a core template block using layout updates. This allows the developer to decouple dependencies and functionality from the block being extended.

See https://medium.com/technogeeks/viewmodels-in-magento-2-7c141acda3c1 for more info.

I have created a live template to add to this repository seen below. If you'd like to add me as a contributor I have many more I can offer as well. Cheers!

> M2 viewmodel.php.php
```
<?php

namespace ${VendorName}\${ModuleName}\ViewModel;

use Magento\Framework\View\Element\Block\ArgumentInterface;

/**
 * Class ${ClassName}
 * ViewModel to inject in template blocks
 */
class ${ClassName} implements ArgumentInterface
{

}

```

**Comment by lfolco** [comment]
I appreciate the comment, but I'm trying to keep these templates rather simple and focus more on the XML-based templates rather than PHP (PHPStorm does a really good job of auto completing classes). Thanks!
